# Generated by Django 2.2.5 on 2020-03-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLocations', models.IntegerField()),
                ('nonWhiteApparel', models.BooleanField()),
                ('colorsF', models.IntegerField()),
                ('colorsB', models.IntegerField()),
                ('colorsR', models.IntegerField()),
                ('colorsL', models.IntegerField()),
                ('colorsSP', models.IntegerField()),
                ('colorsOS', models.IntegerField()),
                ('costPerItem', models.IntegerField()),
                ('margin', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
