# Generated by Django 2.2.5 on 2020-03-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='margin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='nonWhiteApparel',
            field=models.BooleanField(default=True),
        ),
    ]
